services:
  openspoolman:
    image: openspoolman:1.0.7
    container_name: openspoolman
    restart: unless-stopped
    env_file:
      - config.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/home/app/data
      - ./logs:/home/app/logs
      - ./static/prints:/home/app/static/prints
    command:
      - waitress-serve
      - --host=0.0.0.0
      - --port=8000
      - app_custom:app
    environment:
      - TZ=Europe/Berlin
